name: Java CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build-test-docker-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Run tests
      - name: Run tests
        run: mvn test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ordermicroservice-app:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag ordermicroservice-app:latest ${{ secrets.DOCKER_USERNAME }}/ordermicroservice-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ordermicroservice-app:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ordermicroservice-app:latest
            docker stop ordermicroservice-app || true
            docker rm ordermicroservice-app || true
            docker run -d -p 8083:8083 --name ordermicroservice-app ${{ secrets.DOCKER_USERNAME }}/ordermicroservice-app:latest
